### ISSUE TITLE
Materials URL can not access

### ISSUE THREAD

**Issue by spacefan** [gmtsar/2021-unavco-course-GMTSAR#1]
https://drive.google.com/drive/u/2/folders/XXXXXXXX can not access?

**Comment by Xiaohua-Eric-Xu** [comment]
Hi, we don't have any materials uploaded yet so haven't shared the link.

**Comment by Xiaohua-Eric-Xu** [comment]
Now the link should work. Let me know if it doesn't

**Comment by spacefan** [comment]
Its ok now
