### ISSUE TITLE
How to Join?

### ISSUE THREAD

**Issue by nubati** [gmtsar/2021-unavco-course-GMTSAR#2]
hello!
how to join in this course?

thank you

**Comment by Xiaohua-Eric-Xu** [comment]
Did you register through UNAVCO short courses?

**Comment by nubati** [comment]
no, I didn't. I just knew this

**Comment by Xiaohua-Eric-Xu** [comment]
OK. Maybe I'll update the link in the README page early next week.

**Comment by nubati** [comment]
woah. Waiting for the new update. Thank you so much!

**Comment by Xiaohua-Eric-Xu** [comment]
Were you able to join the slack chat room and then the meeting?

**Comment by nubati** [comment]
yes, I were there and joined all of the session..  thank you very much for the link. glad to have joined there.
